export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_REPOS = 'GET_REPOS';
export const NO_REPOS = 'NO_REPOS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADD_WALLET = 'ADD_WALLET';
export const WALLET_ERROR = 'WALLET_ERROR';
export const GET_WALLET = 'GET_WALLET';
export const GET_WALLETS = 'GET_WALLETS';
export const DELETE_WALLET = 'DELETE_WALLET';
export const ADD_TEAM_ACCOUNT = 'ADD_TEAM_ACCOUNT';
export const DELETE_TEAM_ACCOUNT = 'DELETE_TEAM_ACCOUNT';
export const GET_TEAM_ACCOUNT = 'GET_TEAM_ACCOUNT';
export const GET_TEAM_ACCOUNTS = 'GET_TEAM_ACCOUNTS';
export const ADD_TEAM_ERROR = 'ADD_TEAM_ERROR';

export const SEND_NOTIFICATION = 'SEND_NOTIFICATION';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const DELETE_NOTIFICATION_ERROR = 'DELETE_NOTIFICATION_ERROR';


export const GET_BALANCE = 'GET_BALANCE';
export const GET_BALANCE_ERROR = 'GET_BALANCE_ERROR';   
export const REGISTER_ADMIN_SUCCESS = 'REGISTER_ADMIN_SUCCESS'; 

// Timer ACTIONS
export const ACTION_TIMER = 'ACTION_TIMER';